steps:
  # Step 1: Deploy the monthlyBuyFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - monthlyBuyFunction  # The name of the Cloud Function for monthly buys
    - --source=.
    - --trigger-http
    - --project=riseupbi
    - --region=europe-west3
    - --runtime=python311
    - --timeout=540s
    - --entry-point=monthly_buy  # Entry point function in your Python code
    - --memory=256MB

  # Step 2: Deploy the rebalanceFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - rebalanceFunction  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --project=riseupbi
    - --region=europe-west3
    - --runtime=python311
    - --timeout=540s
    - --entry-point=rebalance  # Entry point function in your Python code
    - --memory=256MB

options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Cloud Logging only
