steps:
  #Step 1: Deploy the monthly_buy_hfeaFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - monthly_buy_hfea  # The name of the Cloud Function for monthly buys
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=monthly_buy_hfea  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  #Step 2: Deploy the rebalance_hfeaFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - rebalance_hfea  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=rebalance_hfea  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Step 3: Deploy the monthly_buy_spxl
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - monthly_buy_spxl  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=monthly_buy_spxl  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Deploy the monthly_buy_eet
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - monthly_buy_eet  # The name of the Cloud Function
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=monthly_buy_eet  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Deploy the monthly_buy_efo
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - monthly_buy_efo  # The name of the Cloud Function
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=monthly_buy_efo  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Step 4: Deploy the daily_trade_spxl_200sma
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - daily_trade_spxl_200sma  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=daily_trade_spxl_200sma  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Step 4: Deploy the daily_trade_eet_200sma
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - daily_trade_eet_200sma  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=daily_trade_eet_200sma  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Step 4: Deploy the daily_trade_efo_200sma
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - daily_trade_efo_200sma  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=daily_trade_efo_200sma  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Step 6: Deploy the unified index_alert Cloud Function with Alpaca and Telegram settings
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - index_alert  # Single Cloud Function for all indices
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=index_alert  # Python function entry point
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # # Step 7: Deploy the make_monthly_buy_tqqq
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #   - functions
  #   - deploy
  #   - make_monthly_buy_tqqq  # The name of the Cloud Function for make_monthly_buy_tqqq
  #   - --source=.
  #   - --trigger-http
  #   - --region=europe-west3
  #   - --runtime=python310
  #   - --timeout=540s
  #   - --entry-point=monthly_buy_tqqq  # Entry point function in your Python code
  #   - --memory=256MB
  #   - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782

  # # Step 4: Deploy the buy_tqqq_if_above_200sma
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #   - functions
  #   - deploy
  #   - buy_tqqq_if_above_200sma  # The name of the Cloud Function for buy_tqqq_if_above_200sma
  #   - --source=.
  #   - --trigger-http
  #   - --region=europe-west3
  #   - --runtime=python310
  #   - --timeout=540s
  #   - --entry-point=buy_tqqq_above_200sma  # Entry point function in your Python code
  #   - --memory=256MB
  #   - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782


  # # Step 5: Deploy the sell_tqqq_if_below_200sma
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #   - functions
  #   - deploy
  #   - sell_tqqq_if_below_200sma  # The name of the Cloud Function for sell_tqqq_if_below_200sma
  #   - --source=.
  #   - --trigger-http
  #   - --region=europe-west3
  #   - --runtime=python310
  #   - --timeout=540s
  #   - --entry-point=sell_tqqq_below_200sma  # Entry point function in your Python code
  #   - --memory=256MB
  #   - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782


# Create Cloud Scheduler job for 'monthly_buy_hfea' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'monthly_buy_hfea',
      '--schedule', '0 12 1-7 * *',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/monthly_buy_hfea',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Create Cloud Scheduler job for 'rebalance_hfea' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'rebalance_hfea',
      '--schedule', '0 14 1-7 1,4,7,10 *',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/rebalance_hfea',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Create Cloud Scheduler job for 'monthly_buy_spxl' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'monthly_buy_spxl',
      '--schedule', '0 12 1-7 * *',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/monthly_buy_spxl',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential


  # Create Cloud Scheduler job for 'buy_spxl_above_200sma' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'daily_trade_spxl_200sma',
      '--schedule', '56 15 * * 1-5',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/daily_trade_spxl_200sma',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Create Cloud Scheduler job for 'buy_spxl_above_200sma' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'daily_trade_eet_200sma',
      '--schedule', '56 15 * * 1-5',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/daily_trade_eet_200sma',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # Create Cloud Scheduler job for 'buy_spxl_above_200sma' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'daily_trade_efo_200sma',
      '--schedule', '56 15 * * 1-5',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/daily_trade_efo_200sma',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]
    waitFor: ['-'] # start in parallel and actually needs to be set, otherwise deployment is sequential

  # # Create Cloud Scheduler job for 'monthly_buy_tqqq' function
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: [
  #     'scheduler', 'jobs', 'update', 'http', 'make_monthly_buy_tqqq',
  #     '--schedule', '45 20 3 * *',  
  #     '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/make_monthly_buy_tqqq',
  #     '--http-method', 'POST',
  #     '--time-zone', 'America/New_York',
  #     '--location', 'europe-west3',
  #     '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
  #   ]

  # # Create Cloud Scheduler job for 'buy_tqqq_above_200sma' function
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: [
  #     'scheduler', 'jobs', 'update', 'http', 'buy_tqqq_if_above_200sma',
  #     '--schedule', '53 15 * * 1-5',  
  #     '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/buy_tqqq_if_above_200sma',
  #     '--http-method', 'POST',
  #     '--time-zone', 'America/New_York',
  #     '--location', 'europe-west3',
  #     '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
  #   ]

  # # Create Cloud Scheduler job for 'sell_tqqq_below_200sma' function
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: [
  #     'scheduler', 'jobs', 'update', 'http', 'sell_tqqq_if_below_200sma', #use 'create' instead of 'update' for the first time
  #     '--schedule', '53 15 * * 1-5',  
  #     '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/sell_tqqq_if_below_200sma',
  #     '--http-method', 'POST',
  #     '--time-zone', 'America/New_York',
  #     '--location', 'europe-west3',
  #     '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
  #   ]

  # Cloud Scheduler Job for S&P 500 Index (POST method with request body)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'sp500_drop_alert',
      '--schedule', '30 9-15 * * 1-5',  # Runs at the 30th minute of every hour from 9 AM to 3 PM (inclusive)
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/index_alert',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com',
      '--message-body', '{"index_symbol": "^SPX", "index_name": "S&P 500"}'
    ]

  # Cloud Scheduler Job for MSCI World Index (POST method with request body)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'update', 'http', 'msci_drop_alert',
      '--schedule', '30 9-15 * * 1-5',  # Runs at the 30th minute of every hour from 9 AM to 3 PM (inclusive)
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/index_alert',
      '--http-method', 'POST',
      '--time-zone', 'America/New_York',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com',
      '--message-body', '{"index_symbol": "URTH", "index_name": "MSCI World"}'
    ]

options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Cloud Logging only