steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  # Step 2: Deploy the monthly_buy function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - monthlyBuyFunction
      - --runtime
      - python310
      - --trigger-http
      - --entry-point
      - monthly_buy
      - --timeout
      - '540s'
      - --memory
      - '256MB'
      - --region
      - 'europe-west1'

  # Step 3: Deploy the rebalance function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - rebalanceFunction
      - --runtime
      - python310
      - --trigger-http
      - --entry-point
      - rebalance
      - --timeout
      - '540s'
      - --memory
      - '256MB'
      - --region
      - 'europe-west1'

options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Cloud Logging only

timeout: '600s'
