steps:
  #Step 1: Deploy the monthly_buy_hfeaFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - monthly_buy_hfea  # The name of the Cloud Function for monthly buys
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=monthly_buy_hfea  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782


  #Step 2: Deploy the rebalance_hfeaFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - rebalance_hfea  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=rebalance_hfea  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782


  # Step 3: Deploy the rebalance_hfeaFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - monthly_buy_spxl  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=monthly_buy_spxl  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782

  # Step 4: Deploy the rebalance_hfeaFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - buy_spxl_above_200sma  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=buy_spxl_above_200sma  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782


  # Step 5: Deploy the rebalance_hfeaFunction
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - sell_spxl_below_200sma  # The name of the Cloud Function for rebalancing
    - --source=.
    - --trigger-http
    - --region=europe-west3
    - --runtime=python310
    - --timeout=540s
    - --entry-point=sell_spxl_below_200sma  # Entry point function in your Python code
    - --memory=256MB
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=1098661711782

# Create Cloud Scheduler job for 'monthly_buy_hfea' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'create', 'http', 'monthly_buy_hfea',
      '--schedule', '0 19 3 * *',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/monthly_buy_hfea',
      '--http-method', 'POST',
      '--time-zone', 'UTC',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]

  # Create Cloud Scheduler job for 'rebalance_hfea' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'create', 'http', 'rebalance_hfea',
      '--schedule', '0 19 3 1,4,7,10 *',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/rebalance_hfea',
      '--http-method', 'POST',
      '--time-zone', 'UTC',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]

  # Create Cloud Scheduler job for 'monthly_buy_spxl' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'create', 'http', 'monthly_buy_spxl',
      '--schedule', '0 19 3 * *',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/buy_spxl_above_200sma',
      '--http-method', 'POST',
      '--time-zone', 'UTC',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]

  # Create Cloud Scheduler job for 'buy_spxl_above_200sma' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'create', 'http', 'buy_spxl_above_200sma',
      '--schedule', '45,55 19 * * 1-5',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/buy_spxl_above_200sma',
      '--http-method', 'POST',
      '--time-zone', 'UTC',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]

  # Create Cloud Scheduler job for 'sell_spxl_below_200sma' function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'scheduler', 'jobs', 'create', 'http', 'sell_spxl_below_200sma',
      '--schedule', '45,55 19 * * 1-5',  
      '--uri', 'https://europe-west3-trading-436516.cloudfunctions.net/sell_spxl_below_200sma',
      '--http-method', 'POST',
      '--time-zone', 'UTC',
      '--location', 'europe-west3',
      '--oidc-service-account-email', '1098661711782-compute@developer.gserviceaccount.com'
    ]

options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Cloud Logging only
